# Generate the Ansible inventory so the Tailscale hostname is single-sourced
# from Terraform. Administration/deploys reach the host over Tailscale SSH, so
# ansible_host is the tailnet hostname (requires MagicDNS, or substitute the
# tailscale IP). Written to ../ansible/inventory.ini (gitignored).
resource "local_file" "ansible_inventory" {
  filename = "${path.root}/../ansible/inventory.ini"
  content  = <<-EOT
    # Generated by Terraform — do not edit by hand.
    [dashtec]
    ${var.tailscale_hostname} ansible_user=root

    [dashtec:vars]
    ansible_python_interpreter=/usr/bin/python3
  EOT

  # The server must exist (and be on the tailnet) before the inventory is useful.
  depends_on = [hcloud_server.host]
}
